# Flood Adapt v{{< meta version >}} {.doc .doc-index}

## FloodAdapt

Class that contains the main functionality of FloodAdapt.

| | |
| --- | --- |
| [FloodAdapt](FloodAdapt.qmd#flood_adapt.FloodAdapt) |  |

## Setup and configuration

Configuration settings for FloodAdapt.

| | |
| --- | --- |
| [Settings](Settings.qmd#flood_adapt.Settings) | The configuration settings for the FloodAdapt database and integrator. |
| [Site](Site.qmd#flood_adapt.Site) | The expected variables and data types of attributes of the Site class. |

## Object models

Object models in FloodAdapt are the components that are saved in the database. They define the configuration, input and output of the model kernels. The database stores Objects, and returns Objects when queried.

| | |
| --- | --- |
| [Object](Object.qmd#flood_adapt.objects.object_model.Object) | Base class for FloodAdapt objects. |

### Measures

Various flood protection and mitigation measures available that can interact with the models. Can be impact measures or a hazard measures, where impact measures do not affect the hazard model at all, and hazard measures do.

| | |
| --- | --- |
| [Measure](objects/Measure.qmd#flood_adapt.objects.Measure) | The expected variables and data types of attributes common to all measures. |
| [MeasureType](objects/MeasureType.qmd#flood_adapt.objects.MeasureType) | Class describing the accepted input for the variable 'type' in Measure. |
| [SelectionType](objects/SelectionType.qmd#flood_adapt.objects.SelectionType) | Class describing the accepted input for the variable 'selection_type' in Measures. |
| [FloodWall](objects/FloodWall.qmd#flood_adapt.objects.FloodWall) | The expected variables and data types of the "floodwall" hazard measure. |
| [GreenInfrastructure](objects/GreenInfrastructure.qmd#flood_adapt.objects.GreenInfrastructure) | The expected variables and data types of the "green infrastructure" hazard measure. |
| [Pump](objects/Pump.qmd#flood_adapt.objects.Pump) | The expected variables and data types of the "pump" hazard measure. |
| [Buyout](objects/Buyout.qmd#flood_adapt.objects.Buyout) | The expected variables and data types of the "buyout" impact measure. |
| [Elevate](objects/Elevate.qmd#flood_adapt.objects.Elevate) | The expected variables and data types of the "elevate" impact measure. |
| [FloodProof](objects/FloodProof.qmd#flood_adapt.objects.FloodProof) | The expected variables and data types of the "floodproof" impact measure. |

### Strategies

A collection of measures that can be used to define a strategy for flood risk management.

| | |
| --- | --- |
| [Strategy](objects/Strategy.qmd#flood_adapt.objects.Strategy) | Class representing a strategy in FloodAdapt. |

### Events

Event types including historical, synthetic, and hurricane events.

| | |
| --- | --- |
| [Event](objects/Event.qmd#flood_adapt.objects.Event) | The accepted input for an event in FloodAdapt. |
| [SyntheticEvent](objects/SyntheticEvent.qmd#flood_adapt.objects.SyntheticEvent) | BaseModel describing the expected variables and data types for parameters of Synthetic that extend the parent class Event. |
| [HistoricalEvent](objects/HistoricalEvent.qmd#flood_adapt.objects.HistoricalEvent) | BaseModel describing the expected variables and data types for parameters of HistoricalEvent that extend the parent class Event. |
| [HurricaneEvent](objects/HurricaneEvent.qmd#flood_adapt.objects.HurricaneEvent) | BaseModel describing the expected variables and data types for parameters of HurricaneEvent that extend the parent class Event. |
| [EventSet](objects/EventSet.qmd#flood_adapt.objects.EventSet) | BaseModel describing the expected variables and data types for parameters of EventSet. |
| [TimeFrame](objects/TimeFrame.qmd#flood_adapt.objects.TimeFrame) | Class representing a time frame for a simulation. |
| [IForcing](objects/IForcing.qmd#flood_adapt.objects.IForcing) | BaseModel describing the expected variables and data types for forcing parameters of hazard model. |
| [ForcingType](objects/ForcingType.qmd#flood_adapt.objects.ForcingType) | Enum class for the different types of forcing parameters. |
| [Template](objects/Template.qmd#flood_adapt.objects.Template) | Class describing the accepted input for the variable template in Event. |
| [Mode](objects/Mode.qmd#flood_adapt.objects.Mode) | Class describing the accepted input for the variable mode in Event. |
| [SubEventModel](objects/SubEventModel.qmd#flood_adapt.objects.SubEventModel) | The accepted input for a sub event in FloodAdapt. |

### Projections

Climate and socio-economic projections for future scenario analysis.

| | |
| --- | --- |
| [Projection](objects/Projection.qmd#flood_adapt.objects.Projection) | The accepted input for a projection in FloodAdapt. |
| [PhysicalProjection](objects/PhysicalProjection.qmd#flood_adapt.objects.PhysicalProjection) | The accepted input for a physical projection in FloodAdapt. |
| [SocioEconomicChange](objects/SocioEconomicChange.qmd#flood_adapt.objects.SocioEconomicChange) | The accepted input for socio-economic change in FloodAdapt. |

### Scenarios

Scenario modeling for assessing different flood risk management approaches. Scenarios consist of a combination of event, projection, and strategy.

| | |
| --- | --- |
| [Scenario](objects/Scenario.qmd#flood_adapt.objects.Scenario) | BaseModel describing the expected variables and data types of a scenario. |

### Benefits

Benefit calculation for different flood risk management strategies. Benefits can be used to perform cost benefit analysis on a strategy, which is calculated based on the impact of the event on the population and infrastructure.

| | |
| --- | --- |
| [Benefit](objects/Benefit.qmd#flood_adapt.objects.Benefit) | BaseModel describing the expected variables and data types of a Benefit analysis object. |
| [CurrentSituationModel](objects/CurrentSituationModel.qmd#flood_adapt.objects.CurrentSituationModel) | The accepted input for a current situation in FloodAdapt. |

## Unit system

Unit system for FloodAdapt. The unit system is used to convert between different units of measurement, and to define the units of the input and output of the models.

| | |
| --- | --- |
| [ValueUnitPair](ValueUnitPair.qmd#flood_adapt.unit_system.ValueUnitPair) | Represents a value with associated units. |
| [UnitfulLength](UnitfulLength.qmd#flood_adapt.unit_system.UnitfulLength) | Combination of length and unit. |
| [UnitfulHeight](UnitfulHeight.qmd#flood_adapt.unit_system.UnitfulHeight) | Combination of height and unit. |
| [UnitfulArea](UnitfulArea.qmd#flood_adapt.unit_system.UnitfulArea) | Combination of area and unit. |
| [UnitfulVelocity](UnitfulVelocity.qmd#flood_adapt.unit_system.UnitfulVelocity) | Combination of velocity and unit. |
| [UnitfulDirection](UnitfulDirection.qmd#flood_adapt.unit_system.UnitfulDirection) | Combination of direction and unit. |
| [UnitfulDischarge](UnitfulDischarge.qmd#flood_adapt.unit_system.UnitfulDischarge) | Combination of discharge and unit. |
| [UnitfulIntensity](UnitfulIntensity.qmd#flood_adapt.unit_system.UnitfulIntensity) | Combination of intensity and unit. |
| [UnitfulVolume](UnitfulVolume.qmd#flood_adapt.unit_system.UnitfulVolume) | Combination of volume and unit. |
| [UnitfulTime](UnitfulTime.qmd#flood_adapt.unit_system.UnitfulTime) | Combination of time and unit. |
| [UnitfulLengthRefValue](UnitfulLengthRefValue.qmd#flood_adapt.unit_system.UnitfulLengthRefValue) | Combination of length and unit with a reference value. |
| [UnitTypesLength](UnitTypesLength.qmd#flood_adapt.unit_system.UnitTypesLength) | Units of length. |
| [UnitTypesArea](UnitTypesArea.qmd#flood_adapt.unit_system.UnitTypesArea) | Units of area. |
| [UnitTypesVolume](UnitTypesVolume.qmd#flood_adapt.unit_system.UnitTypesVolume) | Units of volume. |
| [UnitTypesVelocity](UnitTypesVelocity.qmd#flood_adapt.unit_system.UnitTypesVelocity) | Units of velocity. |
| [UnitTypesDirection](UnitTypesDirection.qmd#flood_adapt.unit_system.UnitTypesDirection) | Units of direction. |
| [UnitTypesTime](UnitTypesTime.qmd#flood_adapt.unit_system.UnitTypesTime) | Units of time. |
| [UnitTypesDischarge](UnitTypesDischarge.qmd#flood_adapt.unit_system.UnitTypesDischarge) | Units of discharge. |
| [UnitTypesIntensity](UnitTypesIntensity.qmd#flood_adapt.unit_system.UnitTypesIntensity) | Units of intensity. |
| [VerticalReference](VerticalReference.qmd#flood_adapt.unit_system.VerticalReference) | Vertical reference for height. |
