# Object { #flood_adapt.objects.object_model.Object }

```python
objects.object_model.Object()
```

Base class for FloodAdapt objects.

## Attributes {.doc-section .doc-section-attributes}

<code>[**name**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   Name of the object.

<code>[**description**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   Description of the object. defaults to "".

## Methods

| Name | Description |
| --- | --- |
| [load_file](#flood_adapt.objects.object_model.Object.load_file) | Load object from file. |
| [save](#flood_adapt.objects.object_model.Object.save) | Save object to disk. |
| [save_additional](#flood_adapt.objects.object_model.Object.save_additional) | Save additional files to database if the object has any and update attrs to reflect the change in file location. |

### load_file { #flood_adapt.objects.object_model.Object.load_file }

```python
objects.object_model.Object.load_file(file_path: Path | str | os.PathLike)
```

Load object from file.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**file_path**]{.parameter-name} [:]{.parameter-annotation-sep} [[Path](`pathlib.Path`) \| [str](`str`) \| [os](`os`).[PathLike](`os.PathLike`)]{.parameter-annotation}</code>

:   Path to the file to load.

### save { #flood_adapt.objects.object_model.Object.save }

```python
objects.object_model.Object.save(toml_path: Path | str | os.PathLike)
```

Save object to disk.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**toml_path**]{.parameter-name} [:]{.parameter-annotation-sep} [[Path](`pathlib.Path`) \| [str](`str`) \| [os](`os`).[PathLike](`os.PathLike`)]{.parameter-annotation}</code>

:   Path to the file to save.

### save_additional { #flood_adapt.objects.object_model.Object.save_additional }

```python
objects.object_model.Object.save_additional(
    output_dir: Path | str | os.PathLike,
)
```

Save additional files to database if the object has any and update attrs to reflect the change in file location.

This method should be overridden if the object has additional files.
