repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: check-toml
  - id: check-merge-conflict
  - id: check-added-large-files
    exclude: ^(environment/)$
    args: [--maxkb=10240] # 10MB
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
  - id: ruff
    args: ['--fix', --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/crate-ci/typos
  rev: v1.23.6
  hooks:
  - id: typos
