channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\basemap-1.4.1-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\Cartopy-0.22.0-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\cftime-1.6.3-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\fiona-1.9.5-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\GDAL-3.8.4-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\netCDF4-1.6.5-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\pygeos-0.14.0-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\pyproj-3.6.1-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\rasterio-1.3.9-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\Rtree-1.2.0-cp310-cp310-win_amd64.whl
  - C:\Users\blom_lk\dev\Workspace_FloodAdapt\FloodAdapt\environment\geospatial-wheels\shapely-2.0.3-cp310-cp310-win_amd64.whl
name: test1
