# These are the default values for environment variables.
# They should be overwritten if FloodAdapt is imported as a package!
# Use the functions in config.py to overwrite these at runtime.

DATABASE_ROOT="path/to/svn/database"    # Absolute path to the svn database root
SYSTEM_FOLDER="path/to/system/folder"   # Absolute path to the system folder
DATABASE_NAME="database_name"           # Default database_name (containing the input, output and static folder) used in headless mode (only backend) by tests. This is overwritten if run through the GUI by the contents of flood_adapt_gui.toml.
