# These are the default values for environment variables
# They should be overwritten if FloodAdapt is imported as a package
# Use the functions in config.py to overwrite these at runtime
# IMPORTANT: do not use backslashes in the path or the toml reader will fail
# Use only forward slashes like in the examples


# Path to the svn database root
DATABASE_ROOT="../Database"

# Path to the system folder
SYSTEM_FOLDER="../Database/system"

# Default database_name (containing the input, output and static folder) used in headless mode (only backend) by tests.
DATABASE_NAME="charleston_test"
