name: flood_adapt

channels:
  - conda-forge
  - numba

dependencies:
  - pip
  - pip:
    - NDBC
    - noaa-coops
    - cht-tide
    - cht-meteo
    - cht-observations
    - git+https://github.com/Deltares/hydromt_fiat.git
    - git+https://github.com/Deltares/fiat_toolbox.git
    - git+https://github.com/Deltares/hydromt_sfincs.git@v2/quadtree
    - git+https://github.com/Deltares/cht_cyclones.git
  - black
  - typos
  - ruff
  - build
  - geopandas
  - mypy
  - numpy
  - pandas
  - plotly
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - census
  - pre-commit
  - numpy-financial
  - pyogrio
  - geojson
