name: flood_adapt

channels:
  - conda-forge

dependencies:
  - black
  - build
  - geopandas
  - hydromt
  - hydromt_sfincs
  - mypy
  - numpy
  - pandas
  - pip
  - pip:
    - noaa-coops
    - NDBC
  - plotly
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine