name: flood_adapt

channels:
  - conda-forge

dependencies:
  - pip
  - pip:
    - NDBC
    - git+https://github.com/Deltares/hydromt_fiat.git@fiat_integrator
  - black
  - build
  - geopandas
  - hydromt
  - hydromt_sfincs
  - mypy
  - numpy
  - pandas
  - plotly
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - noaa-coops
  - census
