name: flood_adapt

channels:
  - conda-forge
  - numba

dependencies:
  # Core
  - python=3.10
  - pip
  - pip:
    - NDBC
    - noaa-coops
    - cht-tide
    - cht-meteo
    - cht-observations
    - hydromt_fiat
    - fiat_toolbox
    - git+https://github.com/Deltares/hydromt_sfincs.git@FA_quadtree
    - git+https://github.com/Deltares/cht_cyclones.git
  - pandas
  - geojson
  - geopandas
  - mypy
  - numpy
  - numpy-financial
  - plotly
  - pyogrio
  - pydantic
  - tomli
  - tomli-w
  - census
  
  # Testing
  - pytest
  
  # Distribution
  - build
  - twine

  # Development
  - pre-commit
  - black
  - typos
  - ruff
