name: flood_adapt

channels:
  - conda-forge
  - numba

dependencies:
  # Use conda to install pre-built binaries for geopandas and its C++ dependencies (GDAL, PROJ and fiona)
  # Then `pip install .` to install the rest of the dependencies from the pyproj.toml that are on PyPI
  - python=3.10
  - geopandas
  - pip
  - pip:
    - .[dev]
