name: flood_adapt

channels:
  - conda-forge

dependencies:
  - black
  - build
  - geopandas
  - mypy
  - numpy
  - pandas
  - pip
  - pip:
      - hydromt
      - hydromt_sfincs
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - plotly
