name: flood_adapt

channels:
  - conda-forge
  - numba

dependencies:
  - pip
  - pip:
    - NDBC
    - git+https://github.com/Deltares/hydromt_fiat.git@fiat_integrator
    - noaa-coops
    - cht-tide
    - cht-meteo
    - cht-observations
    - cht-cyclones
    - git+https://github.com/Deltares/hydromt_sfincs.git@storage_volume
  - black
  - ruff
  - build
  - geopandas
  - hydromt
  - mypy
  - numpy
  - pandas
  - plotly
  - pydantic=1.10.9
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - census
  - numpy-financial
