name: flood_adapt

channels:
  - conda-forge

dependencies:
  - pip
  - pip:
    - git+https://github.com/Deltares/hydromt_fiat.git@fiat_integrator
    - git+https://github.com/Deltares/cht_meteo.git
    - git+https://github.com/Deltares/cht_tide.git
    - git+https://github.com/Deltares/cht_observations.git
    - git+https://github.com/Deltares/cht_cyclones.git
  - black
  - ruff
  - build
  - geopandas
  - hydromt
  - hydromt_sfincs
  - mypy
  - numpy
  - pandas
  - plotly
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
