name: flood_adapt

channels:
  - conda-forge

dependencies:
  - black
  - build
  - geopandas
  - mypy
  - numpy
  - pandas
  - pip
  - pip:
      - git+https://github.com/Deltares/hydromt.git@85e7795a9f1972fe4e2a8bf7dd2d941193008574
      - git+https://github.com/Deltares/hydromt_sfincs.git@v1/main
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - plotly
