[project]
name = "flood-adapt"
readme = "README.md"
authors = [
    "Gundula Winter <Gundula.Winter@deltares.nl>",
    "Panos Athanasiou <Panos.Athanasiou@deltares.nl>",
    "Frederique de Groen <Frederique.deGroen@deltares.nl>",
    "Tim de Wilde <Tim.deWilde@deltares.nl>",
    "Julian Hofer <Julian.Hofer@deltares.nl>",
    "Daley Adrichem <Daley.Adrichem@deltares.nl>",
    "Luuk Blom <Luuk.Blom@deltares.nl>",
]
repository = "https://github.com/Deltares-research/FloodAdapt"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = ">3.8"

basemap = ">=1.3"
cartopy = "*"
cftime = ">=1.6"
fiona = ">=1.9"
gdal = "*"
geojson = "*"
geopandas = "*"
netcdf4 = ">=1.6"
numpy  = "<2"
numpy-financial = "*"
pandas = "<2"
plotly = "*"
pydantic = "*"
pygeos = "*"
pyogrio = "*"
pyproj = "*"
rtree = ">=1.2"
shapely = ">=2"
tomli = "*"
tomli-w = "*"

[pypi-dependencies]
cht-cyclones = { git = "https://github.com/deltares/cht_cyclones.git" }
cht-meteo = "*"
cht-observations =  { git = "https://github.com/deltares/cht_observations.git" }
cht-tide = "*"
fiat-toolbox = "*"
hydromt-fiat = { git = "https://github.com/deltares/hydromt_fiat.git", rev = "2c1f0556103edeedcd5aec6b59ff1e3554061df1" }
hydromt-sfincs = { git = "https://github.com/deltares/hydromt_sfincs.git", rev = "97c872499cbcaec6092931e4f0ddea1cb57779ca" }
