[Charts]
    [Charts.Flooded]
        Name = "Flooded"
        Image = "{image_path}/person.png"
    [Charts.Displaced]
        Name = "Displaced"
        Image = "{image_path}/person.png"

[Categories]
    [Categories.LowVulnerability]
        Name = "LowVulnerability"
        Color = "#D5DEE1"
    [Categories.HighVulnerability]
        Name = "HighVulnerability"
        Color = "#88A2AA"

[Slices]
    [Slices.Flooded_Low_Vulnerability_People]
        Name = "Flooded low vulnerability people"
        Query = "FloodedLowVulnerability"
        Chart = "Flooded"
        Category = "LowVulnerability"
    [Slices.Flooded_High_Vulnerability_People]
        Name = "Flooded high vulnerability people"
        Query = "FloodedHighVulnerability"
        Chart = "Flooded"
        Category = "HighVulnerability"
    [Slices.Displaced_Low_Vulnerability_People]
        Name = "Displaced low vulnerability people"
        Query = "DisplacedLowVulnerability"
        Chart = "Displaced"
        Category = "LowVulnerability"
    [Slices.Displaced_High_Vulnerability_People]
        Name = "Displaced high vulnerability people"
        Query = "DisplacedHighVulnerability"
        Chart = "Displaced"
        Category = "HighVulnerability"

[Other]
    [Other.Plot]
        image_scale = 0.15
        numbers_font = 20
        height = 350
        width = 600
    [Other.Title]
        text = "People"
        font = 30
    [Other.Subtitle]
        font = 25
    [Other.Legend]
        font = 20
    [Other.Info]
        text="Hi im the info for the people chart"
        image="https://openclipart.org/image/800px/302413"
        scale=0.1
