[Charts]
    [Charts.Flooded_roads]
        Name = "Flooded Roads"

[Categories]
    [Categories.Slightly_Flooded]
        Name = "Slightly Flooded"
        Color = "#D5DEE1"
        Image = "{image_path}/walking_person.png"
    [Categories.Minor_Flooded]
        Name = "Minor Flooded"
        Color = "#88A2AA"
        Image = "{image_path}/car.png"
    [Categories.Major_Flooded]
        Name = "Major Flooded"
        Color = "#88A2AA"
        Image = "{image_path}/truck.png"
    [Categories.Fully_Flooded]
        Name = "Fully Flooded"
        Color = "#88A2AA"
        Image = "{image_path}/ambulance.png"

[Slices]
    [Slices.Slightly_Flooded]
        Name = "Slightly Flooded"
        Query = "SlightlyFloodedRoads"
        Chart = "Flooded Roads"
        Category = "Slightly Flooded"
    [Slices.Minor_Flooded]
        Name = "Minor Flooded"
        Query = "MinorFloodedRoads"
        Chart = "Flooded Roads"
        Category = "Minor Flooded"
    [Slices.Major_Flooded]
        Name = "Major Flooded"
        Query = "MajorFloodedRoads"
        Chart = "Flooded Roads"
        Category = "Major Flooded"
    [Slices.Fully_Flooded]
        Name = "Fully Flooded"
        Query = "FullyFloodedRoads"
        Chart = "Flooded Roads"
        Category = "Fully Flooded"

[Other]
    [Other.Plot]
        image_scale = 0.1
        numbers_font = 20
        height = 350
        width = 600
    [Other.Title]
        text = "Interrupted roads"
        font = 30
    [Other.Subtitle]
        font = 25
    [Other.Info]
        text="""Hi im the info for the roads chart<br>
                I'm a very long sting<br>
                mostly<br>
                containing<br>
                multiple<br>
                lines"""
        image="{image_path}/info.png"
        scale=0.1
