default_length_units = "feet"
default_distance_units = "miles"
default_area_units = "sf"
default_volume_units = "cf"
default_velocity_units = "knots"
default_direction_units = "deg N"
default_discharge_units = "cfs"
default_intensity_units = "inch/hr"
default_cumulative_units = "inch"
