default_length_units = "meters"
default_distance_units = "meters"
default_area_units = "m2"
default_volume_units = "m3"
default_velocity_units = "m/s"
default_direction_units = "deg N"
default_discharge_units = "m3/s"
default_intensity_units = "mm/hr"
default_cumulative_units = "millimeters"
