aggregateBy = []

# Metrics used in buildings damaged charts

[[queries]]
name = "ResidentialMinorCount"
description = "Number of residences with minor damage"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
long_name = "Res buildings w/ minor flooding (#)"
show_in_metrics_table = "False"

[[queries]]
name = "ResidentialMajorCount"
description = "Number of residences with major damage"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
long_name = "Res buildings w/ major flooding (#)"
show_in_metrics_table = "False"

[[queries]]
name = "ResidentialDestroyedCount"
description = "Number of destroyed residences"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
long_name = "Res buildings destroyed (#)"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialMinorCount"
description = "Number of commercial buildings with minor flooding"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
long_name = "Minor Damaged Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialMajorCount"
description = "Number of commercial buildings with major flooding"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
long_name = "Major Damaged Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialDestroyedCount"
description = "Number of destroyed commercial buildings"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
long_name = "Destroyed Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustrialMinorCount"
description = "Number of industrial buildings with minor flooding"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
long_name = "Minor Damaged Industrial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustrialMajorCount"
description = "Number of industrial buildings with major flooding"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
long_name = "Major Damaged Industrial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustrialDestroyedCount"
description = "Number of destroyed industrial buildings"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
long_name = "Destroyed Industrial Buildings"
show_in_metrics_table = "False"

# Metrics used in people/vulnerability charts

[[queries]]
name = "FloodedHomes"
description = "Number of flooded homes "
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 1.5 AND `Total Damage` > 0"
long_name = "Flooded Homes"
show_in_metrics_table = "False"

[[queries]]
name = "DisplacedHomes"
description = "Number of homes with displaced people"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
long_name = "Homes with Displaced People"
show_in_metrics_table = "False"

# Metrics used in road impacts graph

[[queries]]
name = "SlightlyFloodedRoads"
description = "Roads disrupted for pedestrians"
select = "SUM(`Segment Length`)*0.001"
filter = "`Inundation Depth` > 0.05"
long_name = "Slightly flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "MinorFloodedRoads"
description = "Roads disrupted for cars"
select = "SUM(`Segment Length`)*0.001"
filter = "`Inundation Depth` >= 0.1"
long_name = "Minor flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "MajorFloodedRoads"
description = "Roads disrupted for trucks"
select = "SUM(`Segment Length`)*0.001"
filter = "`Inundation Depth` >= 0.25"
long_name = "Major flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "FullyFloodedRoads"
description = "Roads disrupted for rescue vehicles"
select = "SUM(`Segment Length`)*0.001"
filter = "`Inundation Depth` >= 0.4"
long_name = "Fully flooded roads"
show_in_metrics_table = "False"
