aggregateBy = []

[[queries]]
name = "ExpectedAnnualDamages"
description = "Expected annual damages"
select = "SUM(`Risk (EAD)`)"
filter = ""
long_name = "Expected Annual Damages"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes"
description = "Homes likely to flood (Inundation Depth > 0.2) in 30 year period"
select = "COUNT(*)"
filter = "`Exceedance Probability` > 50"
long_name = "Homes likely to flood in 30-year period (#)"
show_in_metrics_table = "False"

[[queries]]
name = "ImpactedHomes2Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 2-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (2Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP2"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes5Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 5-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (5Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP5"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes10Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 10-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (10Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP10"
show_in_metrics_table = "True"


[[queries]]
name = "ImpactedHomes25Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 25-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (25Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP25"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes50Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 50-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (50Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP50"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes100Y"
description = "Homes impacted (Inundation Depth > 0.25) in the 100-year event"
select = "COUNT(*)"
filter = "`Inundation Depth (100Y)` >= 0.25 AND `Primary Object Type` = 'residential'"
long_name = "Flooded homes RP100"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP1"
description = "Total damage with return period of 1 years"
select = "SUM(`Total Damage (1Y)`)"
filter = ""
long_name = "Total Damage (RP 1)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP2"
description = "Total damage with return period of 2 years"
select = "SUM(`Total Damage (2Y)`)"
filter = ""
long_name = "Total Damage (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP5"
description = "Total damage with return period of 5 years"
select = "SUM(`Total Damage (5Y)`)"
filter = ""
long_name = "Total Damage (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP10"
description = "Total damage with return period of 10 years"
select = "SUM(`Total Damage (10Y)`)"
filter = ""
long_name = "Total Damage (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP25"
description = "Total damage with return period of 25 years"
select = "SUM(`Total Damage (25Y)`)"
filter = ""
long_name = "Total Damage (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP50"
description = "Total damage with return period of 50 years"
select = "SUM(`Total Damage (50Y)`)"
filter = ""
long_name = "Total Damage (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP100"
description = "Total damage with return period of 100 years"
select = "SUM(`Total Damage (100Y)`)"
filter = ""
long_name = "Total Damage (RP 100)"
show_in_metrics_table = "True"
