aggregateBy = []

[[queries]]
name = "FloodedAll"
description = "Number of flooded buildings"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` >= 0.10 AND `Total Damage` > 0"
long_name = "Flooded Homes (#)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageEvent"
description = "Total building damage"
select = "SUM(`Total Damage`)"
filter = "`Primary Object Type` != 'road'"
long_name = "Building damage ($)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalResDamageEvent"
description = "Total residential building damage"
select = "SUM(`Total Damage`)"
filter = "`Primary Object Type` IN ('residential')"
long_name = "Residential building damage ($)"
show_in_metrics_table = "True"

[[queries]]
name = "ResidentialCount"
description = "Number of residential buildings with flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential')  AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Flooded homes (#)"
show_in_metrics_table = "True"

[[queries]]
name = "ResidentialMinorCount"
description = "Number of residences with minor damage"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 0.25 AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Res buildings w/ minor flooding (#)"
show_in_metrics_table = "False"

[[queries]]
name = "ResidentialMajorCount"
description = "Number of residences with major damage"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 2 AND `Inundation Depth` > 1 AND `Total Damage` > 0"
long_name = "Res buildings w/ major flooding (#)"
show_in_metrics_table = "False"

[[queries]]
name = "ResidentialDestroyedCount"
description = "Number of destroyed residences"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Inundation Depth` > 2 AND `Total Damage` > 0"
long_name = "Res buildings destroyed (#)"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialCount"
description = "Number of commercial buildings with flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Flooded businesses (#)"
show_in_metrics_table = "True"

[[queries]]
name = "CommercialMinorCount"
description = "Number of commercial buildings with minor flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Inundation Depth` <= 0.25 AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Minor Damaged Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialMajorCount"
description = "Number of commercial buildings with major flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Inundation Depth` <= 2 AND `Inundation Depth` > 1 AND `Total Damage` > 0"
long_name = "Major Damaged Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "CommercialDestroyedCount"
description = "Number of destroyed commercial buildings"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Inundation Depth` > 2 AND `Total Damage` > 0"
long_name = "Destroyed Commercial Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustryCount"
description = "Number of industrial buildings with flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('industrial')  AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Flooded industrial assets (#)"
show_in_metrics_table = "True"

[[queries]]
name = "IndustryMinorCount"
description = "Number of industrial buildings with minor flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('industrial')  AND `Inundation Depth` <= 0.25 AND `Inundation Depth` > 0 AND `Total Damage` > 0"
long_name = "Minor Damaged Industry Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustryMajorCount"
description = "Number of industrial buildings with major flooding"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('industrial')  AND `Inundation Depth` <= 2 AND `Inundation Depth` > 1 AND `Total Damage` > 0"
long_name = "Major Damaged Industry Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "IndustryDestroyedCount"
description = "Number of destroyed industrial buildings"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('industrial')  AND `Inundation Depth` > 2 AND `Total Damage` > 0"
long_name = "Destroyed Industry Buildings"
show_in_metrics_table = "False"

[[queries]]
name = "SlightlyFloodedRoads"
description = "Roads disrupted for pedestrians"
select = "SUM(`Segment Length [m]`) * 0.001"
filter = "`Inundation Depth` > 0.05"
long_name = "Slightly flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "MinorFloodedRoads"
description = "Roads disrupted for cars"
select = "SUM(`Segment Length [m]`) * 0.001"
filter = "`Inundation Depth` >= 0.1"
long_name = "Minor flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "MajorFloodedRoads"
description = "Roads disrupted for trucks"
select = "SUM(`Segment Length [m]`) * 0.001"
filter = "`Inundation Depth` >= 0.25"
long_name = "Major flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "FullyFloodedRoads"
description = "Roads disrupted for rescue vehicles"
select = "SUM(`Segment Length [m]`) * 0.001"
filter = "`Inundation Depth` >= 0.4"
long_name = "Fully flooded roads"
show_in_metrics_table = "False"
