---
title: "Events"
format: html
---

# FloodAdapt Events

FloodAdapt provides a structured system for defining and managing **hazard events** that can be used for simulation, testing, and analysis. Events are central to the framework, consisting of the time frame of interest as well as all relevant hydrometeorological **forcings** such as:

- Water levels
- Rainfall
- Wind
- River discharge

These forcings can be derived from measurements or generated synthetically to support hypothetical or controlled scenarios. All event data is stored in a database, ensuring reproducibility and consistency across simulation workflows.

## Components of an Event

An event in FloodAdapt consists of 1. a [TimeFrame](../../api_ref/TimeFrame.qmd), and 2. a collection of forcing(s).

A TimeFrame is a combination of the event start and end time.

Forcings in FloodAdapt are modular and extensible, allowing fine control over how each physical process is represented.
For example, synthetic surge and tide can be combined into a single synthetic water level signal using a Gaussian curve for surge and a harmonic function for tide.
You can start building your own events by exploring the API reference or following the structure shown in the example.
The modular design makes it easy to plug in your own forcing data, synthetic models, or customized logic.
You can find a list of all available forcing classes [here]() !TODO!

## Event Types

FloodAdapt supports three types of events:

To see a full example of how to define an event, refer to the following notebooks:

[**Synthetic Event Example**](synthetic_event.ipynb) Programmatically defined using idealized or user-defined characteristics.

[**Historical Event Example**](historical_event.ipynb) Built from real-world observations or reanalysis data.

[**Hurricane Event Example**](hurricane_event.ipynb) Run an offshore hazard model using wind and pressure fields from cyclone tracks to generate the waterlevels for the overland hazard model. Only available when the database has an offshore model.
