---
title:	Hydromt FIAT Graphical User Interface
filters:
  - lightbox
lightbox: auto
---

The Hydromt FIAT Graphical User Interface (GUI) makes the **Delft FIAT** model creation accessible for non-modeling experts and facilitates the process of setting up the **Delft FIAT** model. 

The Hydromt FIAT GUI can be downloaded from the [Deltares website](https://www.deltares-usa.us/product-page/floodadapt-software).

### Installation
To install the Hydromt FIAT GUI simply run the executable **(......exe)** and the software is ready to go. 

### Create the model boundaries

Before you start you must select a model output directory by clicking **File** >> **Select Working Directory**.  
Now you are ready to set up the model. 

There are multiple options on how to create the model boundaries:

  * Draw polygon/ draw box  
  * Upload Sfincs boundaries  
  * Upload file (polygon vector file)

In the following video you can see how to generate the model boundaries by simply drawing a polygon. 

::: {#fig-model_boundaries}

{{< video ../../_static/videos/hydromt_fiat/Generate_Boundaries.mp4 >}}

Create model boundaries using the "Draw Polygon" method.

:::

### Quickbuild
If you set up a model in the United States and do not want to use your own data you can simply choose to work with the **quickbuild**. 

The **quickbuild** downloads the 

* **exposure data** from the National Structure Inventory
* **vulnerability curves** from the FEMA’s Hazus Program
* **social vulnerability index** and **equity** from the census api. 
* **road data** from Open Street Map (OSM)

After you generated the model boundaries you can select the quickbuild option in the same tab in the GUI (@fig-nsi_quickbuild)

::: {#fig-nsi_quickbuild}

{{< video ../../_static/videos/hydromt_fiat/Quickbuild.mp4 >}}

Quickbuild option in the United States.

:::

### Create the exposure data
There are two different databases to download the **exposure data** from, depending on where you want to set up your model:

1. **National Structure Inventory (United States)**
2. **Open Street Map (international)**

Additionally, you can download **road data** from Open Street Map. To do so, simply check the checkbox "Include OSM roads" in the GUI ().

The videos below show the exposure setup using the National Structure Inventory (NSI) database (@fig-nsi_exposure) and the Open  Street Map (OSM) database (@fig-osm_exposure).

::: {#fig-nsi_exposure}

{{< video ../../_static/videos/hydromt_fiat/Exposure_NSI.mp4 >}}

Exposure setup using NSI data.

:::


::: {#fig-osm_exposure}

{{< video ../../_static/videos/hydromt_fiat/Exposure_OSM.mp4 >}}

Exposure setup using OSM data.

:::

### Assign vulnerability curves
As a next step you must assign the vulnerability curves to the exposure data. There are two data sources from which the vulnerability curves are downloaded from, depending on the location of your model:

1. **FEMA Hazus Curves (United States)**
2. **JRC Vulnerability Curves (international)**

The GUI will automatically select the correct default curves for your model based upon your exposure data. Therefore, you only need to add the curves to the model without further adjustment. You can follow the steps in the video below (@fig-vulnerability).

::: {#fig-vulnerability}

{{< video ../../_static/videos/hydromt_fiat/NSI_Vulnerability.mp4 >}}

Assign the default vulnerability curves to the exposure data. 

:::

### Create model
At this point, you are ready to create the **Delft FIAT model**. Verify the data sources in the bottom tab, to make sure they match your expectations. If so, create your model (@fig-create_model).

::: {#fig-create_model}

{{< video ../../_static/videos/hydromt_fiat/Create_model_OSM.mp4 >}}

Create your Delft FIAT model. 

:::

### Additional features

#### Social Vulnerability Index (SVI) and Equity
Delft FIAT allows you to evaluate the equitible distribution of damages and benefits by using the **social vulnerability index** and **equity**. If your model site is located in the United States SVI data can be calculated based upon recent literature. 
However, the user has the freedom to upload any social vulnerability index and/or equity layer in form of a **vector file** (e.g. *.gpkg*, *.geojson*) and assign a value to each asset that overlaps the layer (@fig-additional_attr).

*Gui Instructions*
Follow these instructions when setting up a model in the **United States**

  1. In the top panel, select *"SVI + Equity"*.
  2. In the bottom panel, select the year you wish to download data frame.
  3. Check the checkboxes to download, SVI and/or Equity data.

If your model is setup in a location outside the U.S please refer to Chapter **Additional attributes** for instructions. 

For a detailed demonstration please refer to @fig-additional_attr.

#### Additional attribtues
Not only social vulnerability and/or equity can be linked to the exposure data. Any additional layer (e.g. landuse, administrative boundaries or others) can be imposed (@fig-additional_attr). The additional attribute layer must be a **vector file** (e.g. *.gpkg*, *.geojson*) in the same location of your model. 

*Gui Instructions*
If you wish to impose **SVI** and/or **Equity** follow these intstructions. The same instructions apply 1for any aggregation layer or additional attribute you wish to impose on your model. 

  1. In the top panel, select *"Additional Attributes"*.
  2. In the bottom panel *"Add new Source"*, **select the source** of your vector layer and **load** it into the model. 
  3. In the bottom panel *"Select attribute"*, select the **Attribute ID** from the dropdown menu. If you loaded in your file corretly the drop-down menu includes all columns of your data file. Select the column of the attribute/aggregation you wish to impose on your model. 
  4. In the bottom panel *"Select attribute"*, give your layer a **Label** (free-text). This label will be the header for your new additional attribute/aggregation layer in the output data. 
  5. In the bottom panel *"Select attribute"*, click **Add** to add the new layer and the layer will appear in the table in the bottom panel *"Overview attribute"*. 
  6. In the bottom panel *"Overview attribute"*, you can check the checkbox **"Display Attribute"** to verify the correct output of the vector layer. 
  7. You can repeat this process as many layers as you wish.
  8. As soon you added all the layers you wish to impose, select *"Add to model"* and your new additional attributes/aggregation layer is added to your final model. 

For a detailed demonstration please refer to @fig-additional_attr.

::: {#fig-additional_attr}

{{< video ../../_static/videos/hydromt_fiat/SVI_Additional_Attributes_NSI.mp4 >}}

Create your Delft FIAT model. 

:::
