---
title: 	Benefit Calculation
filters:
  - lightbox
lightbox: auto
---

Flood adaptation measures are designed to reduce flood risk, and are typically evaluated by calculating their risk-reduction **benefits** and the **benefit-cost ratio**, which compares benefits with the implementation and maintenance costs of the measure(s).

FloodAdapt supports users in evaluating the risk-reduction benefits of strategies by automating the benefit calculation and guiding the user in the creation of the scenarios needed to calculate benefits. The [user guide section on benefits](../4_user_guide/benefits.qmd) provides comprehensive guidance on preparing and evaluating benefits in FloodAdapt. This technical documentation is limited to the description of the benefit calculation. 

The benefit calculation uses output from four scenarios:

* The risk **without** the strategy implemented in **current conditions**
* The risk **with** the strategy implemented in **current conditions**
* The risk **without** the strategy implemented in **future conditions**
* The risk **with** the strategy implemented in **future conditions**

When a user runs a benefit analysis in FloodAdapt, the following benefit calculations are carried out:

1. The **risk-reduction benefit under current conditions** is calculated as the difference in the risk without the strategy and with the strategy under the "current" projection (representing current conditions).

2. The **risk-reduction benefit under future conditions** (for the year specified in the end-of-analysis situation) is calculated as the difference in the risk without the strategy and with the strategy under the future projection specified in the end-of-analysis situation when you created your benefit analysis.

3. The **annual risk-reduction benefits** are calculated by linearly interpolating between the risk-reduction benefits under current conditions (in the current year) and the risk-reduction benefits under future conditions (in the end-of-analysis year).

4. The **annual discounted benefits** ($B_d(t)$) are calculated as

    $B_d\ (t)=B(t)/(1+r)^t\ $

    where $B(t)$ is the risk-reduction benefit in year $t$, $t$ is the year since implementation, and $r$ is the discount rate.

5. The **(present value of the) benefits** are calculated as the sum of the annual discounted benefits over the analysis duration ($N$ years).

    $Benefits\ =\ \sum_{t=0}^N B_d\ (t)\ $

**When cost information is provided, FloodAdapt additionally calculates:**

6. The **(present value of the) costs** - calculated only when implementation and/or maintenance costs are provided in the benefit analysis input. This is calculated in the same way as the present value of the benefits:
    $Costs\ =\ \sum_{t=0}^N C_d\ (t)\ $

    where $C_d(t)$ is the discounted cost in year $t$.


7. The **benefit-cost ratio** (BCR) is calculated as the present value of the benefits divided by the present value of the costs.

6. The **net present value** (NPV) is the difference in annual discounted benefits and costs, summed up over the analysis period.

    $NPV\ =\ \sum_{t=0}^N [(B(t)-C(t))/(1+r)^t]\ $

7. The **internal rate of return** (IRR) represents the discount rate at which the NPV would be equal to zero. Higher IRR indicates a better investment, because in this case the benefits weigh strongly against the costs.

:::{.callout-warning}
## Some metrics are only calculated when cost information is provided!
The present value of the costs, benefit cost ratio, net present value, and internal rate of return are only calculated if the user has provided information on implementation and/or maintenance costs when they created their benefit analysis. When this information is not provided, the benefits are calculated, but none of the metrics that require comparison with costs.
:::
