[Charts]
    [Charts.Homes]
        Name = "Homes"
        Image = "{image_path}/house.png"
    [Charts.Businesses]
        Name = "Businesses"
        Image = "{image_path}/cart.png"
    [Charts.Health]
        Name = "Health facilities"
        Image = "{image_path}/hospital.png"
    [Charts.Schools]
        Name = "Schools"
        Image = "{image_path}/school.png"
    [Charts.Emergency]
        Name = "Emergency facilities"
        Image = "{image_path}/firetruck.png"


[Categories]
    [Categories.Minor]
        Name = "Minor"
        Color = "#ffa500"
    [Categories.Major]
        Name = "Major"
        Color = "#ff0000"
    [Categories.Destroyed]
        Name = "Destroyed"
        Color = "#000000"

[Slices]
    [Slices.Minor_Homes]
        Name = "Minor Homes"
        Query = "ResidentialMinorCount"
        Chart = "Homes"
        Category = "Minor"
    [Slices.Major_Homes]
        Name = "Major Homes"
        Query = "ResidentialMajorCount"
        Chart = "Homes"
        Category = "Major"
    [Slices.Destroyed_Homes]
        Name = "Destroyed Homes"
        Query = "ResidentialDestroyedCount"
        Chart = "Homes"
        Category = "Destroyed"
    [Slices.Minor_Businesses]
        Name = "Minor Businesses"
        Query = "CommercialMinorCount"
        Chart = "Businesses"
        Category = "Minor"
    [Slices.Major_Businesses]
        Name = "Major Businesses"
        Query = "CommercialMajorCount"
        Chart = "Businesses"
        Category = "Major"
    [Slices.Destroyed_Businesses]
        Name = "Destroyed Businesses"
        Query = "CommercialDestroyedCount"
        Chart = "Businesses"
        Category = "Destroyed"
    [Slices.Minor_Health]
        Name = "Minor Health"
        Query = "HealthMinorCount"
        Chart = "Health facilities"
        Category = "Minor"
    [Slices.Major_Health]
        Name = "Major Health"
        Query = "HealthMajorCount"
        Chart = "Health facilities"
        Category = "Major"
    [Slices.Destroyed_Health]
        Name = "Destroyed Health"
        Query = "HealthDestroyedCount"
        Chart = "Health facilities"
        Category = "Destroyed"
    [Slices.Minor_Schools]
        Name = "Minor Schools"
        Query = "SchoolsMinorCount"
        Chart = "Schools"
        Category = "Minor"
    [Slices.Major_Schools]
        Name = "Major Schools"
        Query = "SchoolsMajorCount"
        Chart = "Schools"
        Category = "Major"
    [Slices.Destroyed_Schools]
        Name = "Destroyed Schools"
        Query = "SchoolsDestroyedCount"
        Chart = "Schools"
        Category = "Destroyed"
    [Slices.Minor_Emergency]
        Name = "Minor Emergency"
        Query = "EmergencyMinorCount"
        Chart = "Emergency facilities"
        Category = "Minor"
    [Slices.Major_Emergency]
        Name = "Major Emergency"
        Query = "EmergencyMajorCount"
        Chart = "Emergency facilities"
        Category = "Major"
    [Slices.Destroyed_Emergency]
        Name = "Destroyed Emergency"
        Query = "EmergencyDestroyedCount"
        Chart = "Emergency facilities"
        Category = "Destroyed"

[Other]
    [Other.Plot]
        image_scale = 0.15
        numbers_font = 20
        height = 350
        width = 1200
    [Other.Title]
        text = "Building damage"
        font = 30
    [Other.Subtitle]
        font = 25
    [Other.Legend]
        font = 20
    [Other.Info]
        text="""Thresholds:<br>
                Minor: <= 1 feet<br>
                Major: > 1 and <= 6 feet<br>
                Destroyed: > 6 feet<br>"""
        image="https://openclipart.org/image/800px/302413"
        scale=0.1
