---
title: Test to print the pdf
subtitle: Floodadapt Guide
author: "Kathryn Roscoe, Sarah Rautenbach, Lauren Schambach"
nocite: |
  @*
format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
    output-file: "Test_print_docs"
    output-ext:  "pdf"
editor: source
---
<!-- To run please use the terminal : quarto render _make_pdf.qmd --resource-path _static
    source : https://github.com/royal-statistical-society/datavisguide/blob/main/_make_pdf.qmd-->

```{r}
#| echo: false
#| eval: true
# Function to change paths
# Function to change paths
update_image_paths <- function(content) {
  # Replace ../../_static/images/ with ../_static/images/
  updated_content <- gsub("\\.\\./\\..*/_static/images/", "../_static/images/", content)
  updated_content <- gsub("##", "### ", updated_content)
  updated_content <- gsub("###", "#### ", updated_content)

  return(updated_content)
}

# Process QMD function
process_qmd <- function(file, fpath_in = "_static", fpath_out = "_static") {
  doc <- readLines(file)
  end_yaml <- which(doc == "---")[2]
  yaml_header <- doc[1:end_yaml]
  title_line <- yaml_header[grep("title:", yaml_header)]
  title <- sub("title: *", "", title_line)
  out_doc <- doc[seq(end_yaml + 1, length(doc))]

  if (fpath_in != fpath_out) {
    out_doc <- stringr::str_replace_all(out_doc, fpath_in, fpath_out)
  }

  res <- knitr::knit_child(text = out_doc, quiet = TRUE, options = list(eval = FALSE, echo = TRUE))

  # Update image paths in the content
  res <- update_image_paths(res)

  return(list(title = title, content = res))
}

```

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
idx <- process_qmd("1_introduction/index.qmd")
howto <- process_qmd("4_user_guide/index.qmd")
start <- process_qmd("4_user_guide/getting_started.qmd")
site <- process_qmd("4_user_guide/site_tab.qmd")
events <- process_qmd("4_user_guide/events/index.qmd")
historic_events <- process_qmd("4_user_guide/events/historic_events/index.qmd")
historic_events_h <- process_qmd("4_user_guide/events/historic_events/historic_events_hurricane.qmd")
historic_events_g <- process_qmd("4_user_guide/events/historic_events/historic_events_gauged.qmd")
historic_events_u <- process_qmd("4_user_guide/events/historic_events/historic_events_ungauged.qmd")
synthetic_events <- process_qmd("4_user_guide/events/synthetic_events.qmd")
probabilistic_events <- process_qmd("4_user_guide/events/probabilistic_events.qmd")
#projections <- process_qmd("4_user_guide/projections/index.qmd")
projections_c <- process_qmd("4_user_guide/projections/climate.qmd")
projections_se <- process_qmd("4_user_guide/projections/socioEconomi.qmd")
measures <- process_qmd("4_user_guide/measures/index.qmd")
measures_h <- process_qmd("4_user_guide/measures/hydraulic.qmd")
measures_gi <- process_qmd("4_user_guide/measures/green_infa.qmd")
measures_b <- process_qmd("4_user_guide/measures/buildings.qmd")
strategy <- process_qmd("4_user_guide/strategy/index.qmd")
scenarios <- process_qmd("4_user_guide/scenarios/index.qmd")
output <- process_qmd("4_user_guide/output/index.qmd")
compare <- process_qmd("4_user_guide/compare/index.qmd")
benefits <- process_qmd("4_user_guide/benefits.qmd")
setup <- process_qmd("3_setup_guide/index.qmd")
setup_sfincs <- process_qmd("3_setup_guide/SFINCS/index.qmd")
setup_sfincs_2 <- process_qmd("3_setup_guide/SFINCS/hydromt_sfincs_gui.qmd")
setup_delft <- process_qmd("3_setup_guide/Delft_Fiat/index.qmd")
setup_delft_2 <- process_qmd("3_setup_guide/Delft_Fiat/hydromt_fiat_gui.qmd")
setup_risk <- process_qmd("3_setup_guide/risk_analysis.qmd")
setup_db <- process_qmd("3_setup_guide/database.qmd")
technical_docs <- process_qmd("5_technical_docs/index.qmd")
technical_docs_e <- process_qmd("5_technical_docs/EventScenario.qmd")
technical_docs_r <- process_qmd("5_technical_docs/RiskScenario.qmd")
technical_docs_eq <- process_qmd("5_technical_docs/EquityCalc.qmd")
technical_docs_b <- process_qmd("5_technical_docs/BenefitCal.qmd")


cat("\n# ", idx$title, "\n\n")
cat(unlist(idx$content), sep = '\n\n')
cat("\n# ", howto$title, "\n\n")
cat(unlist(howto$content), sep = '\n\n')
cat("\n## ", start$title, "\n\n")
cat(unlist(start$content), sep = '\n\n')
cat("\n## ", site$title, "\n\n")
cat(unlist(site$content), sep = '\n\n')
cat("\n## ", events$title, "\n\n")
cat(unlist(events$content), sep = '\n\n')
cat("\n### ", historic_events$title, "\n\n")
cat(unlist(historic_events$content), sep = '\n\n')
cat("\n#### ", historic_events_h$title, "\n\n")
cat(unlist(historic_events_h$content), sep = '\n\n')
cat("\n#### ", historic_events_g$title, "\n\n")
cat(unlist(historic_events_g$content), sep = '\n\n')
cat("\n#### ", historic_events_u$title, "\n\n")
cat(unlist(historic_events_u$content), sep = '\n\n')
cat("\n### ", synthetic_events$title, "\n\n")
cat(unlist(synthetic_events$content), sep = '\n\n')
cat("\n### ", probabilistic_events$title, "\n\n")
cat(unlist(probabilistic_events$content), sep = '\n\n')
cat("\n## ", projections$title, "\n\n")
cat(unlist(projections$content), sep = '\n\n')
cat("\n## ", projections_c$title, "\n\n")
cat(unlist(projections_c$content), sep = '\n\n')
cat("\n## ", projections_se$title, "\n\n")
cat(unlist(projections_se$content), sep = '\n\n')
cat("\n## ", measuress$title, "\n\n")
cat(unlist(measures$content), sep = '\n\n')
cat("\n## ", measures_h$title, "\n\n")
cat(unlist(measures_h$content), sep = '\n\n')
cat("\n## ", measures_gi$title, "\n\n")
cat(unlist(measures_gi$content), sep = '\n\n')
cat("\n## ", measures_b$title, "\n\n")
cat(unlist(measures_b$content), sep = '\n\n')
cat("\n## ", strategy$title, "\n\n")
cat(unlist(strategy$content), sep = '\n\n')
cat("\n## ", scenarios$title, "\n\n")
cat(unlist(scenarios$content), sep = '\n\n')
cat("\n## ", output$title, "\n\n")
cat(unlist(output$content), sep = '\n\n')
cat("\n## ", compare$title, "\n\n")
cat(unlist(compare$content), sep = '\n\n')
cat("\n## ", benefits$title, "\n\n")
cat(unlist(benefits$content), sep = '\n\n')
cat("\n## ", setup$title, "\n\n")
cat(unlist(setup$content), sep = '\n\n')
cat("\n## ", setup_sfincs$title, "\n\n")
cat(unlist(setup_sfincs$content), sep = '\n\n')
cat("\n## ", setup_sfincs_2$title, "\n\n")
cat(unlist(setup_sfincs_2$content), sep = '\n\n')
cat("\n## ", setup_delft$title, "\n\n")
cat(unlist(setup_delft$content), sep = '\n\n')
cat("\n## ", setup_delft_2$title, "\n\n")
cat(unlist(setup_delft_2$content), sep = '\n\n')
cat("\n## ", setup_risk$title, "\n\n")
cat(unlist(setup_risk$content), sep = '\n\n')
cat("\n## ", setup_db$title, "\n\n")
cat(unlist(setup_db$content), sep = '\n\n')
cat("\n## ", technical_docs$title, "\n\n")
cat(unlist(technical_docs$content), sep = '\n\n')
cat("\n## ", technical_docs_e$title, "\n\n")
cat(unlist(technical_docs_e$content), sep = '\n\n')
cat("\n## ", technical_docs_r$title, "\n\n")
cat(unlist(technical_docs_r$content), sep = '\n\n')
cat("\n## ", technical_docs_eq$title, "\n\n")
cat(unlist(technical_docs_eq$content), sep = '\n\n')
cat("\n## ", technical_docs_b$title, "\n\n")
cat(unlist(technical_docs_b$content), sep = '\n\n')
```
