project:
  type: website
  output-dir: "_site"
  pre-render:
    - version.py
    - api.py
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!PDF_Documentation.qmd"
  post-render:
    - "examples/clear_notebooks.py"

filters:
  - include-code-files
  - interlinks

interlinks:
  sources:
    geopandas:
      url: https://geopandas.org/en/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    python:
      url: https://docs.python.org/3/
    numpy:
      url: https://numpy.org/doc/stable/

metadata-files:
  - user_documentation.yml # user guide + sidebar
  - api_ref/_sidebar.yml  # api reference + sidebar
  - _version.yml          # version information
number-sections: false

quartodoc:
  title: "Flood Adapt v{{< meta version >}}"
  style: pkgdown
  package: flood_adapt
  dir: api_ref
  out_index: api_index.qmd # generates index at: api_ref/api_index.qmd
  render_interlinks: true
  options: # default options for all sections
    include_attributes: true
    include_functions: true
    include_classes: true
    include_inherited: false
    signature_name: "relative"
    children: embedded

  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    # show_source: true # enable when merged: https://github.com/machow/quartodoc/issues/354
    display_name: name

  sections:
    - title: "API"
      package: flood_adapt.api
      desc: "Core API modules that contain functions to interact with the main functionality of FloodAdapt."
      contents:
        - benefits
        - database_builder
        - events
        - measures
        - output
        - projections
        - scenarios
        - static
        - strategies

    - title: "Setup and configuration"
      package: flood_adapt
      desc: "Configuration settings and logging utilities for Flood Adapt."
      contents:
        - Settings
        - FloodAdaptLogging
        - Site

    - title: "Adapters"
      package: flood_adapt.adapter
      desc: "Implementations of the adapters that make the connection between FloodAdapt and its models and databases."
      contents:
        - FiatAdapter
        - SfincsAdapter

    - title: "Database"
      desc: "Database classes that define the structure of the database used in FloodAdapt."
      package: flood_adapt.dbs_classes
      contents:
        - Database
        - DbsBenefit
        - DbsEvent
        - DbsMeasure
        - DbsProjection
        - DbsScenario
        - DbsStatic
        - DbsStrategy
        - DbsTemplate

    - title: "Object models"
      package: flood_adapt.object_model.interface.object_model
      desc: "Object models in FloodAdapt are the components that are saved in the database. They define the configuration, input and output of the model kernels. The database stores IObjectModels, and returns IObjectModels when queried. "
      contents:
        # General
        - IObjectModel

    - subtitle: "Measures"
      package: flood_adapt.object_model
      desc: "Various flood protection and mitigation measures available that can interact with the models. Can be impact measures or a hazard measures, where impact measures do not affect the hazard model at all, and hazard measures do."
      contents:
        # General
        - Measure
        - MeasureType
        - SelectionType

        # Hazard
        - FloodWall
        - GreenInfrastructure
        - Pump

        # Impact
        - Buyout
        - Elevate
        - FloodProof

    - subtitle: "Strategies"
      package: flood_adapt.object_model
      desc: "A collection of measures that can be used to define a strategy for flood risk management."
      contents:
        - Strategy

    - subtitle: "Events"
      package: flood_adapt.object_model
      desc: "Event types including historical, synthetic, and hurricane events."
      contents:
        - Event
        - SyntheticEvent
        - HistoricalEvent
        - HurricaneEvent
        - EventSet
    - subtitle: "Projections"
      package: flood_adapt.object_model
      desc: "Climate and socio-economic projections for future scenario analysis."
      contents:
        - Projection

    - subtitle: "Scenarios"
      package: flood_adapt.object_model
      desc: "Scenario modeling for assessing different flood risk management approaches. Scenarios consist of a combination of event, projection, and strategy."
      contents:
        - Scenario

    - subtitle: "Benefits"
      package: flood_adapt.object_model
      desc: "Benefit calculation for different flood risk management strategies. Benefits can be used to perform cost benefit analysis on a strategy, which is calculated based on the impact of the event on the population and infrastructure."
      contents:
        - Benefit

    - title: "Unit system"
      package: flood_adapt.object_model.io.unit_system
      desc: "Unit system for FloodAdapt. The unit system is used to convert between different units of measurement, and to define the units of the input and output of the models."
      contents:
        # Unitful classes
        - ValueUnitPair
        - UnitfulLength
        - UnitfulHeight
        - UnitfulArea
        - UnitfulVelocity
        - UnitfulDirection
        - UnitfulDischarge
        - UnitfulIntensity
        - UnitfulVolume
        - UnitfulTime
        - UnitfulLengthRefValue

        # Unit enums
        - UnitTypesLength
        - UnitTypesArea
        - UnitTypesVolume
        - UnitTypesVelocity
        - UnitTypesDirection
        - UnitTypesTime
        - UnitTypesDischarge
        - UnitTypesIntensity
        - VerticalReference

website:
  title: "Flood Adapt Documentation"
  repo-url: https://github.com/Deltares-research/FloodAdapt
  repo-actions: [source, issue]
  issue-url: https://github.com/Deltares-research/FloodAdapt/issues/new/choose
  page-navigation: true
  favicon: _static/logo.png
  search:
    location: navbar
    limit: 5
    type: textbox
  back-to-top-navigation: true
  page-footer:
    left: |
      Made possible by:
        <a href="https://www.deltares.nl/en" target="_blank" rel="noreferrer noopener">
          <img
            src="/_static/images/deltares-blue.svg"
            alt="Deltares"
            style="height: 40px;"
          />
        </a>

  navbar:
    logo: _static/logo.png
    title: FloodAdapt
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: User Guide
        href: 4_user_guide/index.qmd
      - text: Setup Guide
        href: 3_setup_guide/index.qmd
      - text: Technical Documentation
        href: 5_technical_docs/index.qmd
      - text: API Reference
        href: api_ref/api_index.qmd

    right:
      - icon: github
        url: https://github.com/Deltares-research/FloodAdapt


format:
  html:
    theme:
      light: [cosmo, _static/theme-light.scss]
      dark: [cosmo, _static/theme-dark.scss]
    css: _static/styles.css
    toc: true
    toc-expand: false
    page-layout: article
    grid:
      content-mode: standard

execute:
  freeze: auto
  cache: true
