project:
  type: website
  output-dir: "_site"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!PDF_Documentation.qmd"
  post-render:
    - "examples/clear_notebooks.py"

filters:
  - include-code-files
  - interlinks
  #  - section-bibliographies

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    numpy:
      url: https://numpy.org/doc/stable/

metadata-files:
  - api/_sidebar.yml

number-sections: false
quartodoc:
  dir: api_ref
  # dynamic: true
  sections:
    - title: flood_adapt
      desc: ""
      contents:
        - name: api.benefits
        - name: api.database_builder
        - name: api.events
        - name: api.measures
        - name: api.output
        - name: api.projections
        - name: api.scenarios
        - name: api.static
        - name: api.strategies
        - name: adapter.fiat_adapter
        - name: adapter.sfincs_adapter
        - name: dbs_classes.dbs_benefit.DbsBenefit
        - name: dbs_classes.dbs_event.DbsEvent
        - name: dbs_classes.dbs_measure.DbsMeasure
        - name: dbs_classes.dbs_projection.DbsProjection
        - name: dbs_classes.dbs_scenario.DbsScenario
        - name: dbs_classes.dbs_static.DbsStatic
        - name: dbs_classes.dbs_strategy.DbsStrategy
        - name: dbs_classes.dbs_template.DbsTemplate
        - name: dbs_classes.database.Database
        - name: object_model.benefit.Benefit
        - name: object_model.direct_impacts.DirectImpacts
        - name: object_model.scenario.Scenario
        - name: object_model.site.Site
        - name: object_model.strategy.Strategy
        - name: misc.log.FloodAdaptLogging
        - name: misc.config.Settings
        - name: misc.config.UnitSystem

  package: flood_adapt

website:
  title: "Flood Adapt Documentation"
  page-navigation: true
  favicon: _static/logo.png
  search:
    location: navbar
    limit: 5
    type: textbox
  back-to-top-navigation: true
  page-footer:
    left: |
      Made possible by:
        <a href="https://www.deltares.nl/en" target="_blank" rel="noreferrer noopener">
          <img
            src="/_static/images/deltares-blue.svg"
            alt="Deltares"
            style="height: 40px;"
          />
        </a>

  navbar: # Create navigation bar on
    logo: _static/logo.png
    title: FloodAdapt
    pinned: true
    right:
      - icon: github
        url: https://github.com/Deltares-research/FloodAdapt

  sidebar:
    border: true
    collapse-level: 1
    style: "docked"
    background: light
    search: true

    contents:
      - text: "Introduction"
        file: 1_introduction/index.qmd
      - section: "User Guide"
        file: 4_user_guide/index.qmd # This contains text before sections start
        contents:
          - "4_user_guide/getting_started.qmd"
          - "4_user_guide/site_tab.qmd"
          - section: "Events"
            file: "4_user_guide/events/index.qmd"
            contents:
              - section: "Historical Events"
                file: "4_user_guide/events/historic_events/index.qmd"
                contents:
                  - "4_user_guide/events/historic_events/historic_events_hurricane.qmd"
                  - "4_user_guide/events/historic_events/historic_events_gauged.qmd"
                  - "4_user_guide/events/historic_events/historic_events_ungauged.qmd"
              - "4_user_guide/events/synthetic_events.qmd"
              - "4_user_guide/events/probabilistic_events.qmd"
          - section: "Projections"
            file: "4_user_guide/projections/index.qmd"
            contents:
              - "4_user_guide/projections/climate.qmd"
              - "4_user_guide/projections/socioEconomic.qmd"
          - section: "Measures"
            file: "4_user_guide/measures/index.qmd"
            contents:
              - "4_user_guide/measures/hydraulic.qmd"
              - "4_user_guide/measures/green_infra.qmd"
              - "4_user_guide/measures/buildings.qmd"
          - "4_user_guide/strategy/index.qmd"
          - "4_user_guide/scenarios/index.qmd"
          - "4_user_guide/output/index.qmd"
          - "4_user_guide/compare/index.qmd"
          - "4_user_guide/benefits.qmd"
      - section: "Setup Guide"
        file: 3_setup_guide/index.qmd
        contents:
          - section: "SFINCS Setup"
            file: "3_setup_guide/SFINCS/index.qmd"
            contents:
              - "3_setup_guide/SFINCS/hydromt_sfincs_gui.qmd"
          - section: "Delft FIAT Setup"
            file: "3_setup_guide/Delft_Fiat/index.qmd"
            contents:
              - "3_setup_guide/Delft_Fiat/hydromt_fiat_gui.qmd"
          - "3_setup_guide/risk_analysis.qmd"
          - "3_setup_guide/database.qmd"
      - section: "Technical docs"
        file: "5_technical_docs/index.qmd"
        contents:
          - "5_technical_docs/EventScenario.qmd"
          - "5_technical_docs/RiskScenario.qmd"
          - "5_technical_docs/EquityCalc.qmd"
          - "5_technical_docs/BenefitCalc.qmd"
      - text: "API reference"
        href: "api_ref/"

format:
  html:
    theme:
      light: [cosmo, _static/theme-light.scss]
      dark: [cosmo, _static/theme-dark.scss]
    css: _static/styles.css
    toc: true
    toc-expand: false
    page-layout: article
    grid:
      content-mode: standard

# bibliography: references.bib
# citeproc: false

execute:
  freeze: auto
  cache: true
