---
name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.11"] # fix tests to support older versions
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/fiat_test

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update environment
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          mamba env update -n floodadapt_docs -f environment_docs.yml

      - name: Setup quarto
        run: |
          sudo apt install -y curl
          sudo apt install -y gdebi-core
          mkdir tmp
          curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb --output tmp/quarto.deb
          chmod +x tmp/quarto.deb
          sudo gdebi -n tmp/quarto.deb

      - name: Setup api & testdata
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          mamba run -n floodadapt_docs python -m pip install tomli-w
          cd docs
          mamba run -n floodadapt_docs python api.py
          mamba run -n floodadapt_docs python -m quartodoc interlinks

      - name: Generate docs
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          source /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate floodadapt_docs
          quarto render docs/ --execute

      - name: Upload to GitHub Pages
        if: ${{ github.event_name != 'pull_request' && !github.event.act }}
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          destination_dir: ./${{ env.DOC_VERSION }}
          keep_files: false
          full_commit_message: Deploy ${{ env.DOC_VERSION }} to GitHub Pages

      - name: Trigger Dispatch
        if: ${{ github.event_name != 'pull_request' && !github.event.act }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: docs-updated
