name: floodadapt_docs

channels:
- conda-forge

dependencies:
- python=3.10
- jupyter-cache
- jupyterlab
- notebook
- matplotlib
- numpy
- pandas
- pip
- regex
- setuptools>=61.0.0
- tomli
- pip:
  - quartodoc
  - nbformat
  - jupyter
