name: floodadapt_docs

channels:
- conda-forge

dependencies:
- python=3.10
- jupyter
- jupyter-cache
- jupyterlab
- notebook
- nbformat
- matplotlib
- numpy
- pandas
- pip
- regex
- sphinx
- sphinx_rtd_theme
- sphinx-markdown-builder
- setuptools>=61.0.0
- tomli
- tomli_w
- pip:
  - quartodoc
