name: Build and Publish Sphinx docs to Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme

      - name: Build docs
        run: |
          make dev_docs html

      - name: Publish to Wiki
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: flood_adapt/api/build/html
          destination_dir: wiki
          keep_files: false
          full_commit_message: Deploy documentation to Wiki
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          repo: ${{ github.repository }}.wiki
