name: Build and Publish Sphinx docs to Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Build docs
      run: |
        # Change to the directory where the Makefile is located
        cd flood_adapt/api

        # Build the documentation
        make html

        # Verify the build output
        ls -la build/html

    - name: Wiki Update
      uses: spenserblack/actions-wiki@v0.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: flood_adapt/api/build/html
  
      