name: API Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Miniforge3
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: floodadapt_docs
        environment-file: docs/environment_docs.yml

    - name: Build wiki
      run: |
        make -C ./dev_docs html

    - name: Publish to Wiki
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git ../wiki

        # Copy the built documentation to the Wiki repo
        cp -r dev_docs/build/html/* ../wiki
        cd ../wiki

        # Set up Git to use the GitHub Actions token for authentication
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        # Commit and push the changes
        git add .
        git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'Update Wiki'
        git push
