name: API Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Miniforge3
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: floodadapt_docs
        environment-file: docs/environment_docs.yml

    - name: debug
      run: conda env list

    - name: Build wiki
      run: |
        sphinx-build ./dev_docs/source ./dev_docs/build
    - name: Sync Wiki
      uses: joeizzard/action-wiki-sync@master
      with:
          username: Deltares-research
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: dev_docs/build
          commit_username: 'github-actions[bot]'
          commit_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update Wiki'
