name: API Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Miniforge3
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: floodadapt_docs
        environment-file: docs/environment_docs.yml

    - name: debug
      run: conda env list

    - name: Build wiki
      run: |
        sphinx-build ./dev_docs/source ./dev_docs/build

    - name: Publish to Wiki
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global  user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        git clone https://github.com/${{ github.repository }}.wiki.git ../wiki

        # Copy the built documentation to the Wiki repo
        cp -r dev_docs/build/* ../wiki
        cd ../wiki


        # Commit and push the changes
        git config --global --add safe.directory .
        git add .
        git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'Update Wiki'
        git push
