name: Build and Publish Sphinx docs to Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Build docs
      run: |
        # Change to the directory where the Makefile is located
        cd flood_adapt/api

        # Build the documentation
        make html

        # Verify the build output
        ls -la build/html

    - name: Publish to Wiki
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Clone the Wiki repository into a directory named '.wiki'
        git clone https://github.com/${{ github.repository }}.wiki.git .wiki

        # Copy the built documentation to the Wiki repo
        cp -r flood_adapt/api/build/html/* .wiki/
        
        # Commit and push the changes
        git add .
        git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'Update Wiki'
        git push
