name: CI
on: push
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install ruff==0.4.8 # Make sure these are the same as the versions in pyproject.toml
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff lint
        run: ruff check .
      - name: Run Ruff format
        run: ruff format

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
