name: Lint and Test

on:
  push:
    branches:
      - setup_automated_testing
  workflow_dispatch:

jobs:
  env_and_test:
    runs-on: self-hosted
    strategy:
      max-parallel: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          activate-environment: flood_adapt
          environment-file: environment.yml
          auto-activate-base: true

      - name: Install Dependencies
        shell: pwsh
        run: |
          conda init
          conda activate flood_adapt
          pip install .
          conda info
          conda list

      - name: Test
        shell: pwsh
        run: pytest tests
