name: CI
on: push
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install ruff==0.4.8 # Make sure these are the same as the versions in pyproject.toml
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check . --fix
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install black==24.1.1 # Make sure these are the same as the versions in pyproject.toml
      - name: Check black version
        run: black --version
      - name: Run black
        run: black --check .

  typos:
    name: Spell Check with Typos 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          paths-ignore: 'docs/_static/**'
