name: Lint and Test

on:
  push:
    branches:
      - setup_automated_testing
  workflow_dispatch:

jobs:
  env_and_test:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          activate-environment: flood_adapt
          environment-file: environment.yml
          auto-activate-base: true
      - run: |
          pip install .
          conda info
          conda list
          pytest tests
